engine:
  base:
    url: http://127.0.0.1:8060

server:
  port: 8070

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8071/auth/oauth/token
      userAuthorizationUri: http://localhost:8071/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8071/auth/user/me
spring:
  thymeleaf:
    cache: false